function dist = objfungen(x, mkfun, y, g, oogcost, oogdistweight)
    disp(x)
    crvlab = mkfun(x);
    
    % Distance of each datapoint from line
    ydist = ...
        sum( ...
            min( ...
                sum( ...
                    ( ...
                        bsxfun(@minus, y, permute(crvlab,[3 2 1])) ...
                    ).^2 , ...
                2) , ...
            [], 3) , ...
        1);
    dist = ydist/size(y,1);
    
    % Distance of each linepoint from data
%     ydist = ...
%         sum( ...
%             min( ...
%                 sum( ...
%                     ( ...
%                         bsxfun(@minus, y, permute(crvlab,[3 2 1])) ...
%                     ).^2 , ...
%                 2) , ...
%             [], 1) , ...
%         3);
%     dist = ydist/size(crvlab,1);
    
    [TF,P2] = isingamut(crvlab,g,'lab');
    if all(TF); fprintf('In gamut, %.2f\n',dist); return; end;
    dist = dist + oogcost + oogdistweight*sum(sum((crvlab(~TF,:)-P2(~TF,:)+10).^2,2))/size(crvlab,1);
    fprintf('Out of gamut, %.2f = %.2f + %.2f + %.2f * %.2f\n',...
        dist, ydist/size(y,1), oogcost, oogdistweight, sum(sum((crvlab(~TF,:)-P2(~TF,:)).^2,2))/size(crvlab,1));
end